pub(crate) mod dev;
pub(crate) mod kolory;
mod podmenu_zdjecia_edycja;
pub(crate) mod style_fn;
pub(crate) mod ui_dds;
pub(crate) mod ui_laczenie_zdjec;
pub(crate) mod ui_pakowanie;
pub(crate) mod ui_rozpakowanie;
pub mod ui_standard;
pub(crate) mod ui_zdjecia_edycja;
