#cargo-features = ["edition2024"]
[package]
name = "ui_iced"
version = "0.4.7"
edition = "2024"

[dependencies]
iced = { workspace = true, features = ["advanced"] }
iced_core = { workspace = true }
enumy = { path = "../enumy" }
chrono = { workspace = true }
futures = { workspace = true }
image_conversion = { path = "../image_conversion" }
binarka = { path = "../binarka" }
sys-locale = { workspace = true }
rfd = { workspace = true }
tokio = { workspace = true }
file_merge = { path = "../file_merge" }
encodery = { path = "../encodery" }
strum = { workspace = true }
dds_ops = { path = "../dds_ops" }
rand = { workspace = true }
lazy_static = { workspace = true }
dirs = { workspace = true }