pub(crate) mod button;
pub(crate) mod styles;
pub(crate) mod colors_n_stuff;
pub(crate) mod slajder;
pub(crate) mod text_place;
pub(crate) mod dropdown;
pub(crate) mod status;
pub(crate) mod oddzielacze;
pub(crate) mod text;
