[package]
name = "enumy"
version = "0.1.7"
edition = "2024"

#[lib]
#crate-type = ["cdylib"] # cdylib oznacza C-Dynamic Library (.dll / .so)

[dependencies]
iced = { workspace = true, features = ["advanced", "svg"] }
#dds = { workspace = true }
strum = { workspace = true, features = ["derive"] }

#libheif-rs = { workspace = true }