pub(crate) mod ui_podmenu_ff;
pub(crate) mod ui_podmenu_jpg;
pub(crate) mod ui_podmenu_lewe;
pub(crate) mod ui_podmenu_png;
pub(crate) mod ui_podmenu_qoi;
pub(crate) mod ui_podmenu_tga;
pub(crate) mod ui_podmenu_webp;
pub(crate) mod ui_podmenu_avif;
pub(crate) mod slidery;
