pub(crate) mod dev;
pub(crate) mod kolory;
pub(crate) mod style_fn;
// pub(crate) mod ui_dds;
// pub(crate) mod ui_laczenie_zdjec;
pub(crate) mod ui_binarka;
pub mod ui_standard;
mod binarka;
pub(crate) mod konwersja;
mod dds;
// mod fn_ogolne;
mod metody_do_wariantow;
pub mod fn_ogolne;
mod ui_dds;
