use enumy::opcje::{OptFormatyKoloruObrazOgólny, OptFormatyKoloruObrazuQoi, OptFormatyKoloruObrazuTga, OptMetodaKompresjiZdjecia, OptRozdzielczościObrazów, OptRozszerzeniaPlikówZdjęciowychZnacznik};
use enumy::statusy::LogTxDoBathKonwersjaZdjęć;

#[derive(Debug,Clone)]
pub enum ZbiorowePrzetwarzanieZdjęćMessage{
    ZdjecieEdycjaZmianaWybraneToggleRozszerzenie(OptRozszerzeniaPlikówZdjęciowychZnacznik),
    ZdjeciaEdycjaZmianaJakosciJpg(u8),
    ZdjeciaEdycjaZmianaProgresJpg,
    ZdjeciaEdycjaZmianaKolorJpg(OptFormatyKoloruObrazOgólny),
    ZdjeciaEdycjaZmianaWybranyJpg,
    ZdjeciaEdycjaZmianaKompresjiPng(u8),
    ZdjeciaEdycjaZmianaWybranyPng,
    ZdjeciaEdycjaZmianaFiltraPng,
    ZdjeciaEdycjaZmianaKolorAlpha(u8, u16),
    ZdjeciaEdycjaZmianaBitDepthPng(OptFormatyKoloruObrazOgólny),
    ZdjeciaEdycjaZmianaAlphaPng,
    DopasujRozdzielczosci(OptRozdzielczościObrazów),
    ZdjeciaEdycjaZmianaWybranyTga,
    ZdjeciaEdycjaZmianaBitDepthTga(OptFormatyKoloruObrazuTga),
    ZdjeciaEdycjaZmianaLosslessWebp,
    ZdjeciaEdycjaZmianaWybranyWebp,
    ZdjeciaEdycjaZmianaJakosciWebp(u8),
    ZdjeciaEdycjaZmianaKolorWebp(OptFormatyKoloruObrazOgólny),
    InitLogStartowy,
    ZdjeciaEdycjaZmianaWybranyFF,
    ZdjeciaEdycjaZmianaKompresjaFF(OptMetodaKompresjiZdjecia),
    ZdjeciaEdycjaZmianaKompresjaWartoscFF(u8),
    ZdjeciaEdycjaZmianaBitDepthQoi(OptFormatyKoloruObrazuQoi),
    ZdjeciaEdycjaZmianaWybranyQoi,
    ZdjeciaZmienPlikInPathChanged(String),
    ZdjeciaZmienFolderInPathChanged(String),
    ZdjeciaZmienFolderOutPathChanged(String),
    ZdjeciaZmienFolderOutPathTenSam(bool),
    ZdjeciaEdycjaZmianaZaszumiania(u8),
    WysylkaDanychDoObrobkiZdjec,
    PostepEdycjaFot(LogTxDoBathKonwersjaZdjęć),
    WybierzPlikInFotoEdycjaPakowanie,
    ZdjecieEdycjaZmianaWybraneToggleKolor(OptRozszerzeniaPlikówZdjęciowychZnacznik,OptFormatyKoloruObrazOgólny),
    ZdjecieEdycjaZmianaWybraneToggleKolorTga(OptRozszerzeniaPlikówZdjęciowychZnacznik,OptFormatyKoloruObrazuTga),
    Nic,
    WybierzFolderInFotoEdycjaPakowanie,
}