use enumy::opcje::{AvifChroma, AvifMetodaKompresji, JpgQuant, JpgSamplingFac, OptFormatyKoloruObrazOgólny, OptFormatyKoloruObrazuAvif, OptFormatyKoloruObrazuQoi, OptFormatyKoloruObrazuTga, OptInterpolacja, OptMetodaKompresjiZdjecia, OptRozdzielczościObrazów, OptRozszerzeniaPlikówZdjęciowychZnacznik};
use enumy::statusy::LogTxDoBathKonwersjaZdjęć;

#[derive(Debug,Clone)]
pub enum ZbiorowePrzetwarzanieZdjęćMessage{
    Rozszerzenia(OptRozszerzeniaPlikówZdjęciowychZnacznik),
    JpgJakość(u8),
    JpgProg,
    JpgSampling(JpgSamplingFac),
    JpgQua(JpgQuant),
    JpgScan(u8),
    PngKompresja(u8),
    WypełnienieAlpha(u8, u16),
    Rozdzielczość(OptRozdzielczościObrazów),
    TgaBdepth(OptFormatyKoloruObrazuTga),
    AvifBdepth(OptFormatyKoloruObrazuAvif),
    AvifSpeed(i32),
    WebpLossless,
    AvifLossyToggle,
    AvifLossy(u8),
    AvifKompresja(AvifMetodaKompresji),
    AvifChroma(AvifChroma),
    WebpJakość(u8),
    FfKompresja(OptMetodaKompresjiZdjecia),
    FfKompresjaVal(u8),
    QoiBdepth(OptFormatyKoloruObrazuQoi),
    PathInText(String),
    PathOutText(String),
    PathOutPathInBool(bool),
    Noising(u8),
    Uruchom,
    Log(LogTxDoBathKonwersjaZdjęć),
    PathInFile,
    Bdepth(OptRozszerzeniaPlikówZdjęciowychZnacznik, OptFormatyKoloruObrazOgólny),
    Nic,
    PathInFolder,
    PathsReset,
    PathOutFolder,
    Interpolacja(String)
}