use enumy::opcje::{AvifChroma, AvifMetodaKompresji, JpgQuant, JpgSamplingFac, OptFormatyKoloruObrazOgólny, OptFormatyKoloruObrazuAvif, OptFormatyKoloruObrazuQoi, OptFormatyKoloruObrazuTga, OptMetodaKompresjiZdjecia, OptRozdzielczościObrazów, OptRozszerzeniaPlikówZdjęciowychZnacznik};
use enumy::statusy::LogTxDoBathKonwersjaZdjęć;

#[derive(Debug,Clone)]
pub enum ZbiorowePrzetwarzanieZdjęćMessage{
    ZdjecieEdycjaZmianaWybraneToggleRozszerzenie(OptRozszerzeniaPlikówZdjęciowychZnacznik),
    ZdjeciaEdycjaZmianaJakosciJpg(u8),
    ZdjeciaEdycjaZmianaProgresJpg,
    ZdjeciaEdycjaZmianaJpgSampling(JpgSamplingFac),
    ZdjeciaEdycjaZmianaJpgQua(JpgQuant),
    ZdjeciaEdycjaZmianaJpgScans(u8),
    ZdjeciaEdycjaZmianaKompresjiPng(u8),
    ZdjeciaEdycjaZmianaKolorAlpha(u8, u16),
    DopasujRozdzielczosci(OptRozdzielczościObrazów),
    ZdjeciaEdycjaZmianaBitDepthTga(OptFormatyKoloruObrazuTga),
    ZdjeciaEdycjaZmianaBitDepthAvif(OptFormatyKoloruObrazuAvif),
    ZdjeciaEdycjaZmianaAvifSpeed(i32),
    ZdjeciaEdycjaZmianaLosslessWebp,
    ZdjeciaEdycjaZmianaAvifToggleLossy,
    ZdjeciaEdycjaZmianaAvifLossy(u8),
    ZdjeciaEdycjaZmianaAvifKompresja(AvifMetodaKompresji),
    ZdjeciaEdycjaZmianaAvifChroma(AvifChroma),
    ZdjeciaEdycjaZmianaJakosciWebp(u8),
    ZdjeciaEdycjaZmianaKompresjaFF(OptMetodaKompresjiZdjecia),
    ZdjeciaEdycjaZmianaKompresjaWartoscFF(u8),
    ZdjeciaEdycjaZmianaBitDepthQoi(OptFormatyKoloruObrazuQoi),
    ZdjeciaZmienFolderInPathChanged(String),
    ZdjeciaZmienFolderOutPathChanged(String),
    ZdjeciaZmienFolderOutPathTenSam(bool),
    ZdjeciaEdycjaZmianaZaszumiania(u8),
    WysylkaDanychDoObrobkiZdjec,
    PostepEdycjaFot(LogTxDoBathKonwersjaZdjęć),
    WybierzPlikInFotoEdycjaPakowanie,
    ZdjecieEdycjaZmianaWybraneToggleKolor(OptRozszerzeniaPlikówZdjęciowychZnacznik,OptFormatyKoloruObrazOgólny),
    Nic,
    WybierzFolderInFotoEdycjaPakowanie,
    ResetujStanWejsciowychSciezekEdycjaFoto,
    WybierzFolderOutFotoEdycjaPakowanie,
}